# -*- coding: utf-8 -*-
"""CompareFacesApi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l82SyurWg_mpT8YKMKH2EkcGziBZE4i_
"""

import cv2
import dlib
import numpy as np
from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/compare-faces', methods=['POST'])

def compare_faces(image1_path, image2_path):
    # Load the face detector and shape predictor from dlib
    detector = dlib.get_frontal_face_detector()
    shape_predictor = dlib.shape_predictor("shape_predictor_68_face_landmarks.dat")

    # Load the images
    image1 = cv2.imread(image1_path)
    image2 = cv2.imread(image2_path)

    # Convert the images to grayscale
    gray1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
    gray2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)

    # Detect faces in the images
    faces1 = detector(gray1)
    faces2 = detector(gray2)

    if len(faces1) == 0 or len(faces2) == 0:
        return jsonify({'result': False})

    # Get the face landmarks for the first face in image 1
    shape1 = shape_predictor(gray1, faces1[0])

    # Create a face descriptor for the first face
    face_descriptor1 = np.array(face_recognition.compute_face_descriptor(image1, shape1))

    for face2 in faces2:
        # Get the face landmarks for the current face in image 2
        shape2 = shape_predictor(gray2, face2)

        # Create a face descriptor for the current face in image 2
        face_descriptor2 = np.array(face_recognition.compute_face_descriptor(image2, shape2))

        # Calculate the Euclidean distance between the two face descriptors
        distance = np.linalg.norm(face_descriptor1 - face_descriptor2)

        if distance < 0.6:  # You can adjust this threshold as per your needs
            return jsonify({'result': True})

    return jsonify({'result': False})


if __name__ == '__main__':
    app.run()